Quan_Ly_Thu_Vien/QuanLyThuVienCNPMNC/Controllers/KhachHangController.cs
using QuanLyThuVienCNPMNC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FuzzySharp;
using FuzzySharp.SimilarityRatio;
using Microsoft.Ajax.Utilities;

namespace QuanLyThuVienCNPMNC.Controllers
{
    public class KhachHangController : Controller
    {
        Quan_Ly_Thu_VienEntities databases = new Quan_Ly_Thu_VienEntities();

        // GET: KhachHang
        public ActionResult Index(string searchTerm)
        {
            if (searchTerm.IsNullOrWhiteSpace())
            {
                return View(databases.SACHes
                    .Where(s => s.TinhTrang == 1)
                    .DistinctBy(s => s.MaDS)
                    .ToList());

            }
            else
            {
                var searchResult = databases.SACHes.ToList()
                                    .Where(s => Fuzz.Ratio(s.DAUSACH.TenSach.ToLower(), searchTerm.ToLower()) >= 30
                                                           || s.DAUSACH.TenSach.ToLower().StartsWith(searchTerm.ToLower())
                                                || Fuzz.Ratio(s.DAUSACH.Theloai.ToLower(), searchTerm.ToLower()) >= 30
                                                           || s.DAUSACH.Theloai.ToLower().StartsWith(searchTerm.ToLower()))
                                    .DistinctBy(s => s.MaDS)
                                    .ToList();
                return View(searchResult);
            }
        }

        public ActionResult Details(string mads)
        {
            return View(databases.SACHes.Where(s => s.MaDS == mads && s.TinhTrang == 1).FirstOrDefault());
        }

    }
}

Quan_Ly_Thu_Vien/QuanLyThuVienCNPMNC/Views/KhachHang/Details.cshtml
@model QuanLyThuVienCNPMNC.Models.SACH
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutKhachHang.cshtml";
}
<style>
    .bg_dt {
        width: 100%;
        background-color: white;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        padding: 20px;
    }
</style>


<div style="width:75%;margin-top:72px;" class="container bg_dt">
    <div class="row">
        <div class="col-sm-6">
            <img style="width:60%;" id="img_sach" src="~/images/cover_not_found.jpg" />
        </div>
        <div class="col-sm-6">
            <dl style="font-size:22px;" class="dl-horizontal">
                <dt>
                    Tên sách
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DAUSACH.TenSach)
                </dd>
                <dt>
                    Mã sách
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MaSach)
                </dd>
                <dt>
                    Nhà xuất bản
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DAUSACH.NhaXuatBan.TenNXB)
                </dd>
                <dt>
                    Ngày xuất bản
                </dt>

                <dd>
                    @Convert.ToDateTime(Model.DAUSACH.NgayXuatBan).ToString("dd/MM/yyyy")
                </dd>
                <dt>
                    Mô tả
                </dt>

                <dd>
                    @{
                        if (Model.MoTa == null)
                        {


                            <p>Hiện chưa có mô tả cho sách này !!!</p>
                        }
                        else
                        {
                            @Html.DisplayFor(model => model.MoTa)
                        }
                    }
                </dd>

            </dl>
        </div>
    </div>
</div>
@*<p>
    @Html.ActionLink("Back to List", "Index")
</p>*@

Quan_Ly_Thu_Vien/QuanLyThuVienCNPMNC/Views/KhachHang/Index.cshtml
@model IEnumerable<QuanLyThuVienCNPMNC.Models.SACH>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutKhachHang.cshtml";
}
<style>
   
</style>

<section class="home" id="home">
</section>

<div class="bg-text">

</div>
<div class="container mt-5">
    <h1 class="text-center">Danh mục sách</h1>
    <div class="mt-5 mb-5">
        @using (Html.BeginForm("Index", "KhachHang", FormMethod.Get))
        {
            <div class="m-auto" style="width:70%;">
                <div style="position: relative;">
                    <input id="sreachInput_search" class="form-control" type="text" name="searchTerm" />
                    <button id="btnSearch_search" class="btn btn-primary" type="submit">
                        <i class="fas fa-search" style="font-size: 24px;"></i>
                    </button>
                </div>
            </div>
        }
    </div>
    <div class="row">
        @foreach (var pro in Model)
        {

            <div class="col-sm-12 col-sm-6 col-md-4 col-lg-3">
                <a href="@Url.Action("Details", "KhachHang", new { mads = pro.MaDS })" class="text-decoration-none">
                    <div class="box_img ">
                        <img id="img_sach" src="~/images/cover_not_found.jpg" />
                        <div class="box_des mt-5 text-center">
                            <p class="Name_sach">@Html.DisplayFor(model => pro.DAUSACH.TenSach)</p>
                            <p class="Cate_sach">@Html.DisplayFor(model => pro.DAUSACH.Theloai)</p>
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
</div>