Quan_Ly_Thu_Vien/QuanLyThuVienCNPMNC/Controllers/ThongTinCaNhanController.cs
using QuanLyThuVienCNPMNC.Models;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyThuVienCNPMNC.Controllers
{
    public class ThongTinCaNhanController : Controller
    {
        Quan_Ly_Thu_VienEntities databases = new Quan_Ly_Thu_VienEntities();
        // GET: ThongTinCaNhan
        [HttpGet]
        public ActionResult Detail()
        {
            NHANVIEN nvSession = (NHANVIEN)Session["user"];

            return View(databases.NHANVIENs.Where(s => s.MaNV == nvSession.MaNV).FirstOrDefault());
        }
        [HttpGet]
        public ActionResult Edit()
        {
            NHANVIEN nvSession = (NHANVIEN)Session["user"];
            return View(databases.NHANVIENs.Where(s => s.MaNV == nvSession.MaNV).FirstOrDefault());
        }

        [HttpPost]
        public ActionResult Edit(HttpPostedFileBase ImageAva, NHANVIEN nv)
        {
            try
            {
                NHANVIEN nvSession = (NHANVIEN)Session["user"];
                if (ImageAva != null)
                {
                    //Lấy tên file của hình được up lên
                    var fileName = Path.GetFileName(ImageAva.FileName);
                    //Tạo đường dẫn tới file
                    var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    //Lưu tên
                    nvSession.ImageAva = fileName;
                    Session["user"] = nvSession;
                    //Save vào Images Folder
                    ImageAva.SaveAs(path);
                }
                nv.ImageAva = nvSession.ImageAva;
                databases.Entry(nv).State = EntityState.Modified;
                databases.SaveChanges();
                TempData["Message"] = "Chinh sua thanh cong !!!";
                return RedirectToAction("Detail");
            }
            catch
            {
                TempData["Error"] = "Error... !!!";
                return RedirectToAction("Detail");
            }
        }
        [HttpPost]
        public ActionResult EditAnh(HttpPostedFileBase ImageAva, NHANVIEN nv)
        {
            try
            {
                if (ImageAva != null)
                {
                    NHANVIEN nvSession = (NHANVIEN)Session["user"];
                    nv = databases.NHANVIENs.Where(s => s.MaNV == nvSession.MaNV).FirstOrDefault();

                    //Lấy tên file của hình được up lên
                    var fileName = Path.GetFileName(ImageAva.FileName);
                    //Tạo đường dẫn tới file
                    var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    //Lưu tên
                    nv.ImageAva = fileName;
                    //Cap nhat lai session
                    nvSession.ImageAva = fileName;
                    Session["user"] = nvSession;
                    //Save vào Images Folder
                    ImageAva.SaveAs(path);
                }
                databases.Entry(nv).State = EntityState.Modified;
                databases.SaveChanges();
                TempData["Message"] = "Chinh sua thanh cong !!!";
                return RedirectToAction("Detail");
            }
            catch
            {
                TempData["Error"] = "Error... !!!";
                return RedirectToAction("Detail");
            }
        }
        [HttpGet]
        public ActionResult ChangePass()
        {
            NHANVIEN nvSession = (NHANVIEN)Session["user"];
            return View(databases.NHANVIENs.Where(s => s.MaNV == nvSession.MaNV).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult ChangePass(string mkCu, string mkMoi, string checkMk, NHANVIEN nv)
        {
            NHANVIEN nvSession = (NHANVIEN)Session["user"];
            nv = databases.NHANVIENs.Where(s => s.MaNV == nvSession.MaNV).FirstOrDefault();
            if (!mkCu.ToString().Equals(nv.MatKhau.Trim()))
            {

                TempData["ErrorPassOld"] = "Ban da nhap sai mat khau cu !!";
                return RedirectToAction("ChangePass");
            }
            if (mkCu.Equals(mkMoi))
            {
                TempData["ErrorLikeOldPass"] = "Mat khau moi khong duoc trung voi mat khau cu !!";
                return RedirectToAction("ChangePass");
            }
            nv.MatKhau = mkMoi;
            databases.Entry(nv).State = EntityState.Modified;
            databases.SaveChanges();
            TempData["Message"] = "Doi mat khau thanh cong !!";
            return RedirectToAction("Detail");

        }

    }
}

Quan_Ly_Thu_Vien/QuanLyThuVienCNPMNC/Views/ThongTinCaNhan/ChangePass.cshtml
@model QuanLyThuVienCNPMNC.Models.NHANVIEN

@{
    ViewBag.Title = "ChangePass";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal bg_dt w-50">
        <h2 class="text-center text-uppercase text-bold">Đổi mật khẩu </h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNV)

        <div class="form-group">
            @Html.HiddenFor(model => model.TenNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.ChucVu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ChucVu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChucVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-12">Nhập mật khẩu cũ </label>
            <div class="col-md-12">
                <input class="form-control" id="mkCu" name="mkCu" type="password" required />
                <span class="field-validation-valid text-danger" data-valmsg-for="mkCu" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-12">Nhập mật khẩu mới </label>
            <div class="col-md-12">
                <input class="form-control" id="mkMoi" name="mkMoi" type="password" required />
                <span class="field-validation-valid text-danger" data-valmsg-for="mkMoi" data-valmsg-replace="true"></span>

            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-12">Nhập lại mật khẩu mới</label>
            <div class="col-md-12">
                <input class="form-control" id="checkMk" name="checkMk" type="password" required />
                <span class="field-validation-valid text-danger" data-valmsg-for="checkMk" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group text-center">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Lưu" id="btnSave" class="btn mr-2" style="background-color: #210cae; color:#fff;" />
                @Html.ActionLink("Quay lại", "Detail", null, new { @class = "btn btn-outline-secondary" })

            </div>
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        const mkMoiInput = document.getElementById("mkMoi");
        const checkMkInput = document.getElementById("checkMk");
        const checkMkError = $('[data-valmsg-for="checkMk"]');

        checkMkInput.addEventListener("input", () => {
            if (mkMoiInput.value !== checkMkInput.value) {
                checkMkError.text("Mật khẩu xác nhận không khớp");
                document.getElementById("btnSave").setAttribute("disabled", true);
            }
            else {
                checkMkError.text("");
                document.getElementById("btnSave").removeAttribute("disabled");
            }
        });
    });
</script>

@if (TempData["ErrorPassOld"] != null)
{
    <script type="text/javascript">
               document.addEventListener('DOMContentLoaded', function () {
                   Swal.fire({
                       title: 'Opps..!!',
                       text: 'Bạn đã nhập sai mật khẩu cũ!!',
                       icon: 'error',
                       confirmButtonText: 'OK'
                   });
        });

    </script>
}
@if (TempData["ErrorLikeOldPass"] != null)
{
    <script type="text/javascript">
               document.addEventListener('DOMContentLoaded', function () {
                   Swal.fire({
                       title: 'Opps..!!',
                       text: 'Mật khẩu mới không được giống mật khẩu cũ',
                       icon: 'error',
                       confirmButtonText: 'OK'
                   });
        });

    </script>
}
@if (TempData["Message"] != null)
{
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function () {
            Swal.fire({
                title: 'Thành công !',
                text: 'Đổi mật khẩu thành côngg!!',
                icon: 'success',
                confirmButtonText: 'OK'
            });
        });
    </script>
}

Quan_Ly_Thu_Vien/QuanLyThuVienCNPMNC/Views/ThongTinCaNhan/Detail.cshtml
@model QuanLyThuVienCNPMNC.Models.NHANVIEN

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        list-style: none;
        font-family: 'Josefin Sans', sans-serif;
    }

    .profile .avatar-box {
        width: 35%;
        padding: 8px 0;
        border-radius: 5px;
        text-align: center;
        color: #fff;
        margin: 0 auto;
    }

        .profile .avatar-box img {
            border-radius: 5px;
            margin-bottom: 10px;
        }

        .profile .avatar-box h4 {
            margin-bottom: 10px;
        }

        .profile .avatar-box p {
            font-size: 12px;
        }

    .profile .detail {
        width: 65%;
        background: #fff;
        padding: 30px 25px;
        border-top-right-radius: 5px;
        border-bottom-right-radius: 5px;
        margin: 0 auto;
    }

        .profile .detail .info,
        .profile .detail .projects {
            margin-bottom: 25px;
        }

            .profile .detail .info h3,
            .profile .detail .projects h3 {
                margin-bottom: 15px;
                padding-bottom: 5px;
                border-bottom: 1px solid #e0e0e0;
                color: #353c4e;
                text-transform: uppercase;
                letter-spacing: 5px;
            }

        .profile .detail .info_data,
        .profile .detail .projects_data {
            display: flex;
            justify-content: space-between;
        }

            .profile .detail .info_data .data,
            .profile .detail .projects_data .data {
                width: 45%;
            }

                .profile .detail .info_data .data h4,
                .profile .detail .projects_data .data h4 {
                    color: #353c4e;
                    margin-bottom: 5px;
                }

                .profile .detail .info_data .data p,
                .profile .detail .projects_data .data p {
                    font-size: 13px;
                    margin-bottom: 10px;
                    color: #919aa3;
                }

    .profile .social_media ul {
        display: flex;
    }

        .profile .social_media ul li {
            width: 45px;
            height: 45px;
            background: linear-gradient(to right,#01a9ac,#01dbdf);
            margin-right: 10px;
            border-radius: 5px;
            text-align: center;
            line-height: 45px;
        }

            .profile .social_media ul li a {
                color: #fff;
                display: block;
                font-size: 18px;
            }

    .bg_dt_ttcn {
        margin-top: 20px !important;
        margin: auto;
        padding: 10px 50px 50px 50px;
        width: 750px;
        background: white;
        border-radius: 20px;
        box-shadow: 6px 4px 8px;
    }
</style>

<div class="bg_dt_ttcn">
    <!--<dl class="dl-horizontal">
    >>>>>>> Stashed changes
            <dt>
                Mã nhân viên
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MaNV)
            </dd>
            <dt>
                Tên nhân viên
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TenNV)
            </dd>

            <dt>
                Chức vụ
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ChucVu)
            </dd>

            <dt>
                Tên tài khoản
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.HiddenFor(model => model.MatKhau)
            </dt>

            <dd>
                @Html.HiddenFor(model => model.MatKhau)
            </dd>
            <dt>
                Avatar
            </dt>

            <dd>
               @* @Html.DisplayFor(model => model.ImageAva)*@
                <img src="~/Images/@Model.ImageAva" alt="Avatar"  style="width:180px; border-radius:100px;text-align:center; align-items:center" />
            </dd>
    <<<<<<< Updated upstream
        </dl>
    =======

        </dl>-->

    <div class="container">
        <!-- Trigger the modal with a button -->
        <!-- Button trigger modal -->
        <div id="myModal" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Đổi ảnh đại diện</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    @using (Html.BeginForm("EditAnh", "ThongTinCaNhan", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="modal-body">
                            <!-- Form controls and fields here -->
                            <form>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <input type="file" id="ImageAva" name="ImageAva" />
                                        @Html.ValidationMessageFor(model => model.ImageAva, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <input type="submit" value="Lưu" class="btn btn-primary" style="background-color: #210cae; color:#fff;" />
                                    </div>
                                </div>
                            </form>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="profile mt-5">
        <div class=" avatar-box text-center">
            <img src="~/Images/@Model.ImageAva" alt="user" width="100%" style="border-radius:380px;"><br />
            <button type="button" class="btn text-blue" data-toggle="modal" data-target="#myModal">Đổi ảnh đại diện</button>
        </div>
        <div class="detail">
            <div class="info">
                <h2 class="text-center text-uppercase text-bold mb-4">Thông tin cá nhân</h2>
                <div class="info_data">
                    <div class="data">
                        <dl class="dl-horizontal">
                            <dt>
                                Họ và Tên
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.TenNV)
                            </dd>
                        </dl>
                    </div>
                    <div class="data">
                        <dl class="dl-horizontal">
                            <dt>
                                Mã nhân viên
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.MaNV)
                            </dd>
                        </dl>
                    </div>
                </div>
                <div class="info_data">
                    <div class="data">
                        <dl class="dl-horizontal">
                            <dt>
                                Chức vụ
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.ChucVu)
                            </dd>
                        </dl>
                    </div>
                    <div class="data">
                        <dl class="dl-horizontal">
                            <dt>
                                Email
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Email)
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <p class="text-center">
        @*        @Html.ActionLink("Edit", "Edit", new { id = Model.MaNV }) |
            @Html.ActionLink("Back to List", "Index")*@

        @Html.ActionLink("Chỉnh sửa", "Edit", null, new { @class = "btn btn-secondary mr-2" })
        @Html.ActionLink("Đổi mật khẩu", "ChangePass", null, new { @class = "btn btn-outline-info" })


    </p>
</div>

@if (TempData["Error"] != null)
{
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function () {
            Swal.fire({
                title: 'Oops..',
                text: 'Lỗi...',
                icon: 'error',
                confirmButtonText: 'OK'
            });
        });
    </script>
}
@if (TempData["Message"] != null)
{
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function () {
            Swal.fire({
                position: 'top-end',
                title: 'Thành công !',
                text: 'Lưu thành công :D',
                icon: 'success',
                confirmButtonText: 'OK',
                timer: 1500
                });
        });
    </script>
}

Quan_Ly_Thu_Vien/QuanLyThuVienCNPMNC/Views/ThongTinCaNhan/Edit.cshtml
@model QuanLyThuVienCNPMNC.Models.NHANVIEN

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


 @using (Html.BeginForm("Edit", "ThongTinCaNhan", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal bg_dt w-50">
        <h2 class="text-center text-uppercase text-bold">Cập nhật thông tin</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNV)

        <div class="form-group">
            <label class="control-label col-md-12">Tên nhân viên </label>
            <div class="col-md-12">
                @{
                    string tenNV = Model.TenNV ?? ""; // Lấy giá trị từ model và kiểm tra nếu là null thì gán giá trị mặc định là ""
                }

                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-12">Chức vụ </label>
            <div class="col-md-12">
                    @Html.EditorFor(model => model.ChucVu, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly",@required="required" } })
                    @Html.ValidationMessageFor(model => model.ChucVu, "", new { @class = "text-danger" })
                </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-12">Tên tài khoản </label>
            <div class="col-md-12">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @type = "email",@required="required" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.HiddenFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-12"> Hình đại diện </label>
            <div class="col-md-12">
                <input type="file" id="ImageAva" name="ImageAva" />
                @Html.ValidationMessageFor(model => model.ImageAva, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-12 col-md-12 text-center">
                <input type="submit" value="Lưu" class="btn mr-2" style="background-color: #210cae; color:#fff;" />
                @Html.ActionLink("Quay lại", "Detail", null, new { @class = "btn btn-outline-secondary" })

            </div>
        </div>
    </div>
}